# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages

    - name: Create target directory
      run: mkdir target

    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1

    - name: Copy generated documentation
      run: cp -rT ./target/doc/html ./gh-pages/doc

    - name: Check for changes
      id: check-doc-changed
      run: |
        cd ./gh-pages
        git add --all
        git diff-index --cached --quiet HEAD -- || echo "::set-output name=has-changed::true"

    - name: Commit changes
      if: steps.check-doc-changed.outputs.has-changed == 'true'
      run: |
        cd ./gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "docs: update documentation"

    - name: Push changes to GitHub Pages
      if: steps.check-doc-changed.outputs.has-changed == 'true'
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: gh-pages
        branch: gh-pages
